src/Entity/Plantes.php
<?php

namespace App\Entity;

use App\Repository\PlantesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlantesRepository::class)
 */
class Plantes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Espece;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cultivar;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="plantes")
     */
    private $imageId;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(string $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getEspece(): ?string
    {
        return $this->Espece;
    }

    public function setEspece(string $Espece): self
    {
        $this->Espece = $Espece;

        return $this;
    }

    public function getCultivar(): ?string
    {
        return $this->Cultivar;
    }

    public function setCultivar(string $Cultivar): self
    {
        $this->Cultivar = $Cultivar;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImageId(): Collection
    {
        return $this->imageId;
    }

    public function addImageId(Image $imageId): self
    {
        if (!$this->imageId->contains($imageId)) {
            $this->imageId[] = $imageId;
            $imageId->setPlantes($this);
        }

        return $this;
    }

    public function removeImageId(Image $imageId): self
    {
        if ($this->imageId->removeElement($imageId)) {
            // set the owning side to null (unless already changed)
            if ($imageId->getPlantes() === $this) {
                $imageId->setPlantes(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Il éxiste déjà un compte avec cette adresse mail")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;        

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\ManyToMany(targetEntity=Qcm::class)
     */
    private $idQcm;

    /**
     * @ORM\ManyToMany(targetEntity=Plantes::class)
     */
    private $formation;

    public function __construct()
    {
        $this->idQcm = new ArrayCollection();
        $this->formation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles []= 'ROLE_USER';

        return array_unique($roles);
        
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    // public function __toString() /*convertir les dates en string */
    // {
    //     // return $this->getRoles();

    // }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Qcm[]
     */
    public function getIdQcm(): Collection
    {
        return $this->idQcm;
    }

    public function addIdQcm(Qcm $idQcm): self
    {
        if (!$this->idQcm->contains($idQcm)) {
            $this->idQcm[] = $idQcm;
        }

        return $this;
    }

    public function removeIdQcm(Qcm $idQcm): self
    {
        $this->idQcm->removeElement($idQcm);

        return $this;
    }

    /**
     * @return Collection|Plantes[]
     */
    public function getFormation(): Collection
    {
        return $this->formation;
    }

    public function addFormation(Plantes $formation): self
    {
        if (!$this->formation->contains($formation)) {
            $this->formation[] = $formation;
        }

        return $this;
    }

    public function removeFormation(Plantes $formation): self
    {
        $this->formation->removeElement($formation);

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\PlantesRepository;
use App\Repository\ImageRepository;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Plantes;
use App\Entity\Image;

class HomeController extends AbstractController
{
    #[Route('/home', name: 'home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    
    #[Route('/home/plantes', name: 'listing')]
    public function ToutLesPlantes( PlantesRepository $plantesRepository): Response
    {
        
        $Plantes = $plantesRepository->findAll() ;
        
        return $this->render('home/test.html.twig', [
            'Plantes' => $Plantes
        ]);
    }


    #[Route('/home/plantes/{id}', name: 'single')]
    public function showSingleEvent(int $id, PlantesRepository $plantesRepository, ImageRepository $imageRepository): Response
    {
        $Culti = $imageRepository->findBy(array('plantes'=> $id)) ;

        $tab_img = [];

        foreach($Culti as $item)
        {
            $tab_img [] = $item->getImage();
        }      
        
        $Plante = $plantesRepository->find($id) ;
        if (!$Plante) {
            throw $this->createNotFoundException('La table est vide');
        }
        
        if (!$Culti) {
            throw $this->createNotFoundException('La table est vide');
        }

        return $this->render('home/single.html.twig', [
            'Plante' => $Plante,
            'tabImg' => $tab_img

        ]);        
    }
    
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ouvrier du paysage
{% endblock %}

{% block body %}
	<link rel="stylesheet" href="{{ asset('../styles/accueil.css')}}" >

	<div id="gotobot">
		<a class="arrow d-flex justify-content-center align-items-center" href="#plant">
			<i class="bi bi-arrow-down"></i>
		</a>
	</div>

	<div id="gototop" class="d-none">
		<a class="arrow d-flex justify-content-center align-items-center" onclick="topFunction()">
			<i class="bi bi-arrow-up"></i>
		</a>
	</div>

	<div id="plant" data-spy-target="plant">
		<i class="fab fa-pagelines fa-5x p-md-0" onclick="topFunction()"></i>
	</div>
	
	<div class="img" id="plante">
		<span>Plantes</span>
	</div>
	<section class="p-5">
		<h2>Description</h2>
		<p>En cliquant sur l'un des boutons ci-dessous vous aurez la possiblité de soit faire un quiz sur des plantes ou alors de vous renseigner sur tout type de plante.</p>
	</section>
	<div class="img" id="arbre">
		<span>Arbres</span>
	</div>
	<section class="p-0 pt-5 pb-5">
		<h2>Choix</h2>
		<div id="quizz" class="flex-column flex-md-row col-11 col-md-10 col-lg-12 p-0 justify-content-between justify-content-lg-around mx-auto">
			{% if app.user %} 
				<a href="quizz" class="btn btn-violet my-2 me-2 p-1 p-lg-3 col-5 col-md-3 align-self-center">QUIZ</a>
			{% else %}
				<a href="login" class="btn btn-violet my-2 me-2 p-1 p-lg-3 col-5 col-md-3 align-self-center">QUIZ</a>
			{% endif %}
			{% if app.user %}
				<a href="" class="btn btn-violet my-2 me-2 p-1 p-lg-3 col-5 col-md-3 align-self-center disabled">A VENIR</a>
			{% else %}
				<a href="login" class="btn btn-violet my-2 me-2 p-1 p-lg-3 col-5 col-md-3 align-self-center disabled">A VENIR</a>
			{% endif %}
			{% if app.user %}
				<a href="{{ url('listing') }}" class="btn btn-violet my-2 me-2 p-1 p-lg-3 col-5 col-md-3 align-self-center">PLANTES</a>
			{% else %}
				<a href="login" class="btn btn-violet my-2 me-2 p-1 p-lg-3 col-5 col-md-3 align-self-center">PLANTES</a>
			{% endif %}
		</div>
	</section>
	<div class="img" id="fleur">
		<span>Fleurs</span>
	</div>
	<aside>
		
	</aside>
	<div class="img" id="fin">
	</div>
	
{% endblock %}

templates/home/single.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{Plante.nom}}
{% endblock %}
			
{% block body %}
<link rel="stylesheet" href="{{ asset('../styles/plante.css')}}">

<main class="centre container-fluid">

	<div id="back" class="">
		<a class="arrow d-flex justify-content-center align-items-center" href="../plantes">
			<i class="bi bi-arrow-left"></i>
		</a>
	</div>

	<div id="gototop" class="d-none">
		<a class="arrow d-flex justify-content-center align-items-center" onclick="topFunction()">
			<i class="bi bi-arrow-up"></i>
		</a>
	</div>

	<div class="row">
		<h1 class="text-center mt-3 mb-lg-5">{{Plante.nom}}</h1>
		<div class="my-5 d-flex flex-wrap justify-content-around">
			<img src=" {{ asset('images/plantes/' ~ Plante.image ) }} " class="img-fluid mb-2" alt="{{ Plante.image }}">
			{% for image in tabImg %}
			<img src=" {{ asset('images/plantes/' ~ image  ) }} " class="img-fluid mb-2" alt="{{ image }}">
			{% endfor %}
		</div>
		<div class="renseignement d-md-flex justify-content-md-evenly">
			<p class="fw-bold col-md-3 text-center">Cultivar : {{ Plante.cultivar }}</p>
			<p class="fw-bold col-md-3 text-center">Genre : {{ Plante.genre }}</p>
			<p class="fw-bold col-md-3 text-center">Espèce : {{ Plante.espece }}</p>
		</div>
		<div class="mt-3 mb-5">
			<h1 class="text-center">Description</h1>
			<p class="fs-5 text-justify px-5 col-lg-7 mx-auto">{{Plante.description}}</p>
		</div>
	</div>
</main>

<div class="img" id="fin"></div>

<script src="../script/plante.js"></script>


{% endblock %}

templates/home/test.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DocumentationController!
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{ asset('../styles/plantes.css')}}">


<div id="gototop" class="d-none">
	<a class="arrow d-flex justify-content-center align-items-center" onclick="topFunction()">
		<i class="bi bi-arrow-up"></i>
	</a>
</div>

<main class="centre container-fluid">
			<div class="row d-flex justify-content-evenly">
			
{% for Plante in Plantes %}
<div class="card col-6 col-md-3 mx-md-1 my-4 col-lg-2">
        
        <img src="{{ asset('images/plantes/' ~ Plante.image )}}" class="card-img-top rounded-circle align-self-center mt-4" alt="...">
        <div class="card-body d-flex flex-column justify-content-end">
            <h5 class="card-title text-center">{{ Plante.nom }}</h5>
        </div>
        <a href="{{ url('home') }}/plantes/{{ Plante.id }}" class="btn btn-violet mb-2 text-center fs-4 d-block mx-auto" style="height: 3rem; width: 100%;">Voir</a>
</div>
{% endfor %}
			</div>
</main>

<div class="img" id="fin"></div>

<script src="../script/plantes.js"></script>
{% endblock %}